version: 2

models:

  # - name: mart_collections_portfolio
  #   description: "Comprehensive collections portfolio view linking delinquency, credit, and NPS data"
  #   columns:
  #     - name: loan_id
  #       description: "Primary key"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: customer_id
  #       description: "Foreign key to customers"
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('stg_customers')
  #             field: customer_id
  #     - name: current_outstanding_balance
  #       description: "Current balance owed"
  #       tests:
  #         - not_null
  #         - dbt_utils.accepted_range:
  #             min_value: 0
  #     - name: current_days_past_due
  #       description: "Days past due"
  #       tests:
  #         - not_null
  #         - dbt_utils.accepted_range:
  #             min_value: 0
  #     - name: collection_priority
  #       description: "Priority level for collections"
  #       tests:
  #         - accepted_values:
  #             values: ['current', 'low', 'medium', 'high', 'severe', 'critical']
  #     - name: recovery_likelihood
  #       description: "Likelihood of recovery"
  #       tests:
  #         - accepted_values:
  #             values: ['very_low', 'low', 'medium', 'high']
              
  # - name: mart_credit_nps_analysis
  #   description: "Analysis linking credit metrics with NPS scores for customer insights"
  #   tests:
  #     - dbt_utils.expression_is_true:
  #         expression: "current_credit_score between 300 and 850"
  #     - dbt_utils.expression_is_true:
  #         expression: "latest_nps_score between 0 and 10 or latest_nps_score is null"
  #   columns:
  #     - name: customer_id
  #       description: "Primary key"
  #       tests:
  #         - unique
  #         - not_null
  #     - name: credit_nps_alignment
  #       description: "Correlation between credit trajectory and NPS"
  #       tests:
  #         - accepted_values:
  #             values: ['positive_correlation', 'negative_correlation', 'neutral_correlation', 'mixed_signals']
  #     - name: customer_risk_profile
  #       description: "Risk profile based on credit and NPS"
  #       tests:
  #         - accepted_values:
  #             values: ['high_risk_detractor', 'low_risk_promoter', 'engaged_subprime', 'at_risk_prime', 'standard']
  #     - name: customer_engagement_score
  #       description: "Engagement score 0-100"
  #       tests:
  #         - dbt_utils.accepted_range:
  #             min_value: 0
  #             max_value: 100
              
  # - name: int_loan_performance
  #   description: "Intermediate model combining loan, payment, and delinquency data"
  #   columns:
  #     - name: loan_id
  #       tests:
  #         - unique
  #         - not_null
  #     - name: loan_paydown_ratio
  #       tests:
  #         - dbt_utils.accepted_range:
  #             min_value: 0
  #             max_value: 1.5  # Allow slight over-payment scenarios
              
  # - name: int_customer_credit_history
  #   description: "Consolidated customer credit history and trends"
  #   columns:
  #     - name: customer_id
  #       tests:
  #         - unique
  #         - not_null
  #     - name: current_credit_score
  #       tests:
  #         - dbt_utils.accepted_range:
  #             min_value: 300
  #             max_value: 850
  #     - name: credit_trajectory
  #       tests:
  #         - accepted_values:
  #             values: ['improving', 'declining', 'stable']
              
  # - name: int_customer_nps
  #   description: "Consolidated customer NPS responses and sentiment"
  #   columns:
  #     - name: customer_id
  #       tests:
  #         - unique
  #         - not_null
  #     - name: latest_nps_category
  #       tests:
  #         - accepted_values:
  #             values: ['promoter', 'passive', 'detractor']